<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>msc</string>
	</array>
	<key>name</key>
	<string>MSCGen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>msc\s*\{</string>
			<key>comment</key>
			<string>Just a basic scope for error prevention</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.body</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mscgen</string>
	<key>uuid</key>
	<string>e49e950f-fac2-4f70-acde-dfd2c996cc8d</string>
</dict>
</plist>
